# ---------------------------------------------------------------------------
# Key Pair — auto-generated by Terraform
# ---------------------------------------------------------------------------
# 1. tls_private_key generates a 4096-bit RSA key in memory
# 2. The PUBLIC half is uploaded to AWS as an EC2 Key Pair
# 3. The PRIVATE half is saved to vprofile-dev.pem in this directory
#    → use it to SSH:  ssh -i vprofile-dev.pem ubuntu@<public_ip>
#
# ⚠️  Add "*.pem" to your .gitignore — never commit private keys.
# ---------------------------------------------------------------------------

# Generate the RSA key pair in memory
resource "tls_private_key" "vprofile" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# Upload the public key to AWS
resource "aws_key_pair" "vprofile" {
  key_name   = "${var.project_name}-${var.environment}-keypair"
  public_key = tls_private_key.vprofile.public_key_openssh

  tags = {
    Name = "${var.project_name}-${var.environment}-keypair"
  }
}

# Save the private key as a .pem file next to your terraform files
resource "local_sensitive_file" "private_key_pem" {
  content         = tls_private_key.vprofile.private_key_pem
  filename        = "${path.module}/${var.project_name}-${var.environment}.pem"
  file_permission = "0600"
}
